apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-short-cluster.fullname" . }}-user-db-service
  labels:
    {{- include "url-short-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-db-service
spec:
  selector:
    {{- include "url-short-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user-db-pod
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.port.userDb }}
      targetPort: {{ .Values.port.userDb }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-short-cluster.fullname" . }}-url-db-service
  labels:
    {{- include "url-short-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: url-db-service
spec:
  selector:
    {{- include "url-short-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: url-db-pod
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.port.urlDb }}
      targetPort: {{ .Values.port.urlDb }}
